### ISSUE TITLE
Reloads the previous code and resetting the selected language as python

### ISSUE THREAD

**Issue by cozerCode** [lines-of-codes/CodeTyper#2]
<h3>Hi,</h3>
I think that i got a problem and when I reload the page, it just shows the previous language's code and resetting the selected language as python.
here is what I mean <br>
(also this is  cursed) <br>

![image](https://user-images.githubusercontent.com/86025456/144715711-19a5d8a6-e915-4fb9-b028-99dba54311ea.png)

ans when i start typing it just kinda crashes the website when i don't type slowley ?

**Comment by lines-of-codes** [comment]
Yeah, That's a known problem, Will fix it \:p

**Comment by lines-of-codes** [comment]
Fixed
